### PR TITLE
develop

### PR DESCRIPTION
**Pull request by kirokoNjenga**
*What does this PR do *
-Mobile responsive website 
-w3c validator tested 
-stylelint for CSS test passed
-Great project learned a lot

### CODE REVIEW

**Comment by shshamim63** [comment]
## :white_check_mark:  [!! Changes Required!!] :white_check_mark: 
___
Hi @Samkiroko :wave: ,
Amazing job on this project. Items are rendering, where they should. Contains descriptive readme. PR consists a summary. Awesome :clap: . Just one main issue is blocking me to approve this project. 
___
#### Please follow the instruction below to complete this project
___
### :spades: [Mandatory Changes] :spades: 
___
1. Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload.) And you were asked to do so ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright). I can see some errors in there. Please solve those errors.
___
#### Please fix the above mentioned issue and send  another review request 
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Review by mosesogwo — CHANGES_REQUESTED** [review]
## Hi @Samkiroko, @tunedev
**You have done a good job but this project is about responsive design and you'll require more changes to :airplane:. Please take care of the following requirements:**
> **Navigation should change to a hamburger on small screens:**
 - **Your copy:** 
image

- **Original:** 
image

> **The top 3 articles section should switch to one column on small screens**
- **Your copy:**
image

- **Original:**
image

> On small screens, the latest news section should be aligned in one column, with text to the side of the image.
- **Your copy: **
image
- **Original:** 
image

> Similarly, the **latest funding section** should be aligned, one column per row on small screens. I won't add the screenshot here again.

> Also in the **Categories (Apps, GEAR, Tech, etc) section,** and **Latest deals section**  ensure alignment is one column per row on small screens.

**Comment by kirokoNjenga** [comment]
@mosesogwo 
-have tested the site with my phone it works perfectly here are some screen shot
image
image
image

**Review by mosesogwo — APPROVED** [review]
### @Samkiroko, @tunedev - Great project! :clap: 
Sorry about the earlier review. Chrome responsive design mode wasn't rendering it properly for small screens. I have just tried with Firefox and it works properly.

**You are good to :airplane:**.

### Status: Approved!

**Pull request merged**
